name: Node.js CI with Cloudflare Tunnel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start Node.js app
      run: npm start &
      # run in background

    - name: Install official cloudflared
      run: |
        curl -LO https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
        sudo chmod +x /usr/local/bin/cloudflared

    - name: Start Cloudflare Tunnel (no token)
      run: |
        # Start tunnel and log URL
        cloudflared tunnel --url http://localhost:3000 > tunnel.log 2>&1 &
        sleep 5
        # Print the public URL
        grep -oE 'https://.*trycloudflare.com' tunnel.log
